const AUDIENCE_NAMES: Record<string, string> = {
  "aud-steve-jony": "The Visionary Executive (Steve Jobs + Jony Ive)",
  "aud-shreyas-linus": "The Critical Builder (Linus Torvalds + Shreyas Doshi)",
  "aud-gary-seth": "The Growth Marketer (Gary Vee + Seth Godin)",
  "aud-andrew-ng": "Andrew Ng (CEO, Landing AI · GP, AI Fund)",
  "aud-eli-chen": "Eli Chen (CTO, AI Fund · Ex-Credo AI)",
  "aud-mike-rubino": "Mike Rubino (Head of Talent, AI Fund · Ex-Neuralink)",
  "aud-trade-cfo": "CFO (Import-Heavy Enterprise)",
  "aud-trade-counsel": "Trade Compliance Counsel",
  "aud-trade-ops": "Supply Chain VP",
  "aud-health-cmo": "Hospital CMO",
  "aud-health-researcher": "Principal Investigator (PhD)",
  "aud-health-advocate": "Patient Advocacy Director"
};

interface CachedAdaptation {
  adaptedContent: string;
  rationale: {
    kept: string[];
    simplified: string[];
    expanded: string[];
    cut: string[];
    terminologyChanges: { original: string; adapted: string; reason: string }[];
    gaps: string[];
  };
  reliability: number;
}

interface DemoOrg {
  id: string;
  name: string;
  type: string;
  description: string;
}

interface DemoDoc {
  title: string;
  documentType: string;
  sectionCount: number;
  conceptCount: number;
  tag: string;
  tagColor: string;
  description: string;
  organizations: DemoOrg[];
  adaptations: Record<string, CachedAdaptation>;
}

const DEMO_DOCS: Record<string, DemoDoc> = {
  "doc-eval-demo": {
    title: "Palantir Apollo: Continuous Deployment for the Edge",
    documentType: "Architecture Brief",
    sectionCount: 3,
    conceptCount: 3,
    tag: "Defense Tech",
    tagColor: "indigo",
    description: "Autonomous deployment to air-gapped environments",
    organizations: [
      { id: "org-palantir", name: "Palantir Technologies", type: "company", description: "Enterprise data intelligence platform. Apollo enables AI model deployment to air-gapped and edge environments." },
      { id: "org-ai-fund", name: "AI Fund", description: "Andrew Ng venture studio building AI-native companies.", type: "company" },
    ],
    adaptations: {
      "aud-steve-jony": {
        adaptedContent: "## Why Apollo Matters\n\nPalantir solved a problem nobody else would touch: **how do you push software updates to places with no internet?**\n\nThink military bases in remote locations, oil rigs, classified government facilities — environments where \"just deploy to the cloud\" is laughable.\n\n### The Core Insight\n\nMost deployment systems assume connectivity. Apollo assumes the opposite. It packages everything — code, dependencies, configuration — into a self-contained unit that can evaluate its own environment, decide if it's safe to deploy, and roll back autonomously if something breaks.\n\nNo human in the loop. No phone-home to a central server. The software makes the call.\n\n### What Makes This Different\n\n**Autonomous decision-making at the edge.** The control plane doesn't just push updates — it reasons about constraints. If the math doesn't work, it doesn't deploy. If it deploys and something breaks, it reverses itself.\n\n**This is the future of all software deployment**, not just defense. Every enterprise with distributed operations faces the same problem.\n\n### The Bottom Line\n\nApollo turns deployment from a prayer into a guarantee.",
        rationale: { kept: ["Core autonomous deployment concept — the product's reason to exist", "Edge computing and disconnected environment focus — key differentiator", "Self-healing rollback — trust-builder for risk-averse buyers"], simplified: ["Control plane architecture → 'reasons about constraints'", "Dependency resolution → 'self-contained unit'", "Network topology → 'places with no internet'"], expanded: ["Added real-world analogies (military bases, oil rigs)", "Connected to broader industry trend beyond defense", "Reframed rollback as emotional benefit"], cut: ["API specification details", "Version compatibility matrices", "Benchmark numbers — story matters more"], terminologyChanges: [{ original: "Continuous Deployment Pipeline", adapted: "autonomous update system", reason: "Outcomes, not DevOps jargon" }, { original: "Air-gapped environments", adapted: "places with no internet", reason: "Visceral and immediate" }, { original: "Constraint satisfaction engine", adapted: "reasons about constraints", reason: "Humanized" }], gaps: ["ROI metrics — cost-of-failure vs. cost-of-Apollo. Ask author: average cost of a failed deployment?", "Customer proof points — who else uses this? Ask author: deployment success rates before/after?", "Timeline to value — how fast from install to first autonomous deployment?"] },
        reliability: 94
      },
      "aud-shreyas-linus": {
        adaptedContent: "## Apollo: Architecture Assessment\n\n### What It Actually Does\n\nDeployment orchestrator for air-gapped environments. The core loop:\n\n1. **Package** — Bundles code, runtime deps, config into a versioned, signed artifact\n2. **Evaluate** — On-device constraint solver: disk, memory, CPU, network, deps, security policy\n3. **Deploy or Abort** — All constraints pass → atomic deploy. Any fail → abort. No partial states.\n4. **Monitor + Rollback** — Health checks against SLIs. Auto-rollback if thresholds breach.\n\n### The Hard Technical Problem\n\nConstraint solver runs **entirely locally** with zero connectivity:\n- No remote config fetches\n- Dependency resolution pre-computed and bundled\n- Rollback works without phoning home\n- Clock drift across disconnected nodes is a real edge case\n\n### Architecture Trade-offs\n\n**Correctness over speed.** Constraint evaluation is synchronous and blocking. Right call for defense, wrong for CI/CD-heavy environments.\n\n**Bundling over streaming.** Monolithic packages, not incremental diffs. Larger transfers but eliminates partial-update failures.\n\n### What Could Break\n\n- Constraint explosion at scale — O(n²) worst case\n- No canary/progressive rollout — all-or-nothing per node\n- Artifact size on bandwidth-constrained links\n\n### Verdict\n\nSolid for its target domain. Every trade-off favors reliability over velocity. Would not use for web apps. Would absolutely use where failed deploys have physical-world consequences.",
        rationale: { kept: ["Full deployment lifecycle", "Constraint solver architecture", "Trade-off analysis — correctness vs speed"], simplified: ["Marketing language → technical specifics", "Buzzwords → concrete mechanisms"], expanded: ["Failure mode analysis", "Explicit architecture trade-offs", "Verdict with use-case boundaries"], cut: ["Business value propositions", "Customer testimonials", "Competitive positioning"], terminologyChanges: [{ original: "autonomous continuous deployment", adapted: "deployment orchestrator for air-gapped environments", reason: "Precise vs marketing" }, { original: "secure node", adapted: "versioned, signed artifact", reason: "Specific format matters" }, { original: "evaluates environment constraints", adapted: "on-device constraint solver", reason: "Names the pattern" }], gaps: [] },
        reliability: 96
      },
      "aud-gary-seth": {
        adaptedContent: "## Stop Deploying Software. Start Deploying Confidence.\n\n**The hook:** Every DevOps team has a war story about The Deploy That Broke Everything. Apollo makes that story impossible.\n\n### Platform-Native Angles\n\n**LinkedIn (B2B):**\n\"A single failed deployment to an air-gapped site costs $50-200K. Apollo eliminates 95% of those failures. The math is obvious.\"\n\n**Twitter/X (developers):**\n\"What if your deployment system was smarter than your best SRE? Apollo evaluates 50+ constraints and rolls back faster than you can open a terminal. No internet required.\"\n\n**Blog (thought leadership):**\nThe future of deployment isn't faster CI/CD. It's autonomous systems that never panic, never forget a dependency, and never deploy on a Friday at 4:59 PM.\n\n### Campaign Arc\n\n**Day 1 (curiosity):** Customer war story + tease\n**Day 2 (conversion):** Live demo video — deploy → constraint check → rollback in 30 sec\n**Day 3 (credibility):** Technical deep-dive blog\n\n### One-Line Pitch\n\n\"Apollo is autopilot for software deployment — it flies the plane, checks the weather, and lands safely even when the tower goes dark.\"",
        rationale: { kept: ["Core value prop — autonomous reliability", "Emotional hook — fear of failed deployments", "Constraint solver as differentiator"], simplified: ["Architecture → autopilot metaphor", "Air-gapped → 'when the tower goes dark'", "Constraint satisfaction → 'smarter than your best SRE'"], expanded: ["Platform-specific angles (LinkedIn, Twitter, blog)", "Campaign arc (curiosity → conversion → credibility)", "Customer testimonial framing"], cut: ["Internal architecture details", "Benchmark numbers without context", "Competitive positioning — lead with pain"], terminologyChanges: [{ original: "Continuous Deployment Pipeline", adapted: "autopilot for software deployment", reason: "Metaphor > jargon" }, { original: "constraint satisfaction engine", adapted: "smarter than your best SRE", reason: "Personified comparison" }, { original: "autonomous rollback", adapted: "lands safely when the tower goes dark", reason: "Works on every platform" }], gaps: ["Real customer quote — campaign needs a NAMED testimonial. Ask author: named customer story?", "Demo video — Day 2 needs a 30-sec screen recording. Ask author: can you record a live demo?", "Competitor list — what do teams use instead? Ask author: top 3 alternatives customers evaluated?"] },
        reliability: 91
      }
    }
  },

  "doc-demo-landing": {
    title: "Landing AI: Visual Inspection Quality Report — Q1 2026",
    documentType: "Quality Report",
    sectionCount: 5,
    conceptCount: 4,
    tag: "Manufacturing AI",
    tagColor: "orange",
    description: "Computer vision defect detection for PCB assembly lines",
    organizations: [
      { id: "org-landing-ai", name: "Landing AI", type: "company", description: "Computer vision platform for manufacturing quality inspection. Portfolio company of the AI Fund." },
      { id: "org-ai-fund", name: "AI Fund", type: "company", description: "Andrew Ng venture studio building AI-native companies." },
    ],
    adaptations: {
      "aud-steve-jony": {
        adaptedContent: "## Every Defective Product That Reaches a Customer Is a Broken Promise\n\nLanding AI's visual inspection system looked at 2.4 million circuit boards last quarter. It found defects that human inspectors missed — **not sometimes, but consistently.** 847 defective units caught before shipping. Zero false shipments in the final month.\n\n### Why This Matters\n\nA defective PCB in a medical device isn't a warranty claim. It's a patient at risk. A defective PCB in an automotive module isn't a recall — it's a family on a highway. Quality inspection isn't a manufacturing problem. It's a human safety problem.\n\n### What Changed\n\nThe old process: human inspectors examining boards under magnification, 8 hours a day, catching 92% of defects. The 8% they missed? That's 192,000 defective units per year at this production volume.\n\nThe new process: AI sees every board, every angle, every time. **99.7% detection rate.** The humans now review only the edge cases the AI flags — the ambiguous 3% where human judgment actually matters.\n\n### The Insight\n\nThis isn't AI replacing humans. It's AI handling the repetitive visual grind so humans can focus on the judgment calls that require experience and intuition. The inspector's job got more interesting, not eliminated.",
        rationale: { kept: ["Detection accuracy (99.7%) — the core proof point", "Volume processed (2.4M boards) — proves scale", "Human-AI collaboration model — the Landing AI philosophy"], simplified: ["Statistical methodology → '847 defective units caught'", "Model architecture → 'AI sees every board, every angle'", "False positive rates → 'zero false shipments'"], expanded: ["Connected defects to human safety (medical, automotive)", "Reframed as human-AI collaboration, not replacement", "Added emotional stakes — broken promise to customers"], cut: ["Model training pipeline details", "GPU infrastructure specifications", "Confusion matrix breakdowns"], terminologyChanges: [{ original: "convolutional neural network", adapted: "AI vision system", reason: "The mechanism matters less than the outcome" }, { original: "precision-recall trade-off", adapted: "catching defects without false alarms", reason: "Outcome language" }, { original: "edge inference latency", adapted: "real-time inspection", reason: "Speed is the experience, latency is the implementation" }], gaps: ["Cost savings — this persona needs dollar impact. Ask author: cost per defective unit reaching a customer vs. cost of the AI system?", "Customer quotes — which manufacturing partners are using this? Ask author: named case study with before/after?", "Expansion roadmap — what other inspection types are next? Ask author: Q2 product roadmap?"] },
        reliability: 95
      },
      "aud-shreyas-linus": {
        adaptedContent: "## Visual Inspection Pipeline: Technical Assessment\n\n### Architecture\n\n**Two-stage detection pipeline:**\n1. **Primary classifier** — ResNet-50 backbone, fine-tuned on 50K labeled defect images. Runs on-device (NVIDIA Jetson) at 15 FPS per camera.\n2. **Secondary verifier** — Ensemble of 3 models (different architectures) for flagged items. Majority vote determines final classification. Adds 200ms latency per flagged board.\n\n### Key Metrics (Q1 2026)\n\n| Metric | Value |\n|---|---|\n| Boards inspected | 2.4M |\n| True positive rate | 99.7% |\n| False positive rate | 2.1% |\n| Throughput | 15 FPS/camera |\n| Edge inference latency | 67ms (P99) |\n\n### What Works\n\n- **Edge deployment** eliminates cloud dependency — critical for manufacturing floor latency requirements\n- **Ensemble secondary stage** catches what single-model misses, with minimal latency penalty\n- **Active learning loop** — human-reviewed edge cases feed back into training quarterly\n\n### What Could Break\n\n- **Novel defect types** not in training data — the model fails silently on unseen failure modes\n- **Camera calibration drift** over time — no disclosed automated recalibration\n- **Single-board focus** — no cross-board pattern detection (e.g., systematic defects from a failing machine)\n\n### Verdict\n\nProduction-grade for known defect categories. The active learning loop is the right architecture for continuous improvement. Missing: anomaly detection for unknown defect types and upstream root-cause correlation.",
        rationale: { kept: ["Two-stage pipeline architecture", "Key metrics table with real numbers", "Edge deployment rationale"], simplified: ["Marketing claims → verified metrics", "General statements → specific architecture"], expanded: ["Failure mode analysis (novel defects, calibration drift, cross-board patterns)", "Architecture trade-offs", "Verdict with limitations"], cut: ["Business ROI claims", "Customer success stories", "Market positioning"], terminologyChanges: [{ original: "AI-powered inspection", adapted: "ResNet-50 + ensemble secondary stage", reason: "Name the actual architecture" }, { original: "industry-leading accuracy", adapted: "99.7% TPR / 2.1% FPR", reason: "Numbers, not adjectives" }, { original: "real-time processing", adapted: "67ms P99 on Jetson", reason: "Specific hardware and latency" }], gaps: [] },
        reliability: 96
      },
      "aud-gary-seth": {
        adaptedContent: "## \"We Found 847 Defects Last Quarter That Humans Missed.\"\n\nThat's the LinkedIn headline. That's the hook. That's the entire top-of-funnel strategy.\n\n### Platform Playbook\n\n**LinkedIn (manufacturing decision-makers):**\n\"Our inspectors are great. They catch 92% of defects. But 8% of 2.4 million boards is 192,000 defective units per year. We added AI vision. Now we catch 99.7%. The 847 saves from last quarter alone paid for the system 3x over.\"\n\n**Twitter/X (AI/tech audience):**\n\"Running ResNet-50 on a Jetson at 15 FPS to inspect PCBs. 99.7% detection rate. The interesting part? Humans now only review the ambiguous 3%. Their job got better, not eliminated. 🧵\"\n\n**YouTube/Demo video:**\nSplit-screen: left side shows human inspector under magnification, right side shows AI overlay highlighting defects in real-time. Same board, same defects — AI catches one the human missed. 30 seconds. No narration needed.\n\n### Campaign Arc\n\n**Day 1:** \"847 defects caught\" stat + factory floor photo\n**Day 2:** 30-sec split-screen demo video\n**Day 3:** \"AI didn't replace our inspectors — it made them better\" human interest story\n\n### The Pitch in 10 Words\n\n\"AI catches what humans miss. Humans judge what AI can't.\"",
        rationale: { kept: ["847 caught defects — the viral-worthy number", "99.7% vs 92% comparison — instant credibility", "Human-AI collaboration narrative — disarms the 'AI taking jobs' objection"], simplified: ["Technical pipeline → split-screen demo concept", "Statistical methodology → '8% of 2.4M = 192K defective units'", "Model architecture → 'AI vision'"], expanded: ["Platform-specific content (LinkedIn, Twitter, YouTube)", "Campaign arc with specific daily cadence", "10-word pitch distillation"], cut: ["All model architecture details — marketers distribute stories, not architectures", "Confusion matrices and P99 latencies", "Training pipeline and data collection methodology"], terminologyChanges: [{ original: "true positive rate 99.7%", adapted: "catches 99.7% of defects", reason: "Active voice, human-readable" }, { original: "edge inference on NVIDIA Jetson", adapted: "AI overlay highlighting defects in real-time", reason: "Visual description > hardware spec" }, { original: "active learning loop", adapted: "the system gets smarter every quarter", reason: "Benefit language" }], gaps: ["Named customer — need a real company name for the LinkedIn post. Ask author: can we name the manufacturing partner?", "Factory floor photo/video — the campaign needs real visual assets. Ask author: do we have permission to film on the production line?", "Cost per defect — 'paid for itself 3x' needs a real number. Ask author: what's the cost when a defective board reaches a customer?"] },
        reliability: 92
      },
      "aud-andrew-ng": {
        adaptedContent: "## Q1 Visual Inspection: What the Data Tells Us\n\nI want to focus on three things from this quarter's report.\n\n### 1. The Data-Centric Signal Is Working\n\n99.7% detection rate is strong, but the number I care about is the **active learning loop efficiency**. We're feeding human-reviewed edge cases back into training quarterly. The question is: is our data flywheel actually compounding? If the false positive rate dropped from Q4's 3.1% to Q1's 2.1%, that's a meaningful signal that the data-centric approach — improving the data, not the model — is working.\n\n**Action item:** I want to see a quarter-over-quarter trend on FPR. If we're consistently improving by 0.5-1% per quarter through better labeling alone, that validates our core thesis.\n\n### 2. The Edge Deployment Bet Is Paying Off\n\n67ms P99 on Jetson means we're not bottlenecking the line. The factory doesn't need to slow down for AI — the AI keeps up with the factory. This is the right architecture: inference at the edge, training in the cloud, data curation as the competitive moat.\n\n### 3. What Concerns Me\n\n**Novel defect detection.** We're excellent at finding defects we've seen before. We have no answer for defects we haven't seen. A systematic failure in a new component from a new supplier won't match any training pattern. We need an anomaly detection layer — not just classification of known defects, but flagging of \"this looks different from anything I've been trained on.\"\n\nThis is the next product investment. Anomaly detection for unknown unknowns.\n\n### Bottom Line\n\nThe data-centric flywheel is working. Edge deployment is validated. Next priority: anomaly detection for novel defect types. Let's discuss at the next product review.",
        rationale: { kept: ["99.7% detection rate — the core proof point he'll reference in board meetings", "Active learning loop — validates the data-centric AI thesis he's built his career on", "Edge deployment latency — proves the architecture scales"], simplified: ["Statistical methodology → 'what the data tells us'", "Model architecture details → focused on the data flywheel, not the model"], expanded: ["Added data-centric framing — this is Andrew's core philosophy", "Connected to next product investment (anomaly detection)", "Added specific action items — he thinks in decisions, not reports"], cut: ["General ML background — he wrote the textbook", "ROI calculations — he's the CEO, he knows the economics", "Competitor comparisons — irrelevant at this altitude"], terminologyChanges: [{ original: "ResNet-50 backbone", adapted: "the model", reason: "Andrew cares about the data pipeline, not the architecture choice" }, { original: "false positive rate 2.1%", adapted: "FPR dropped from Q4's 3.1% to Q1's 2.1%", reason: "Trend matters more than snapshot" }, { original: "edge inference", adapted: "AI keeps up with the factory", reason: "Outcome framing" }], gaps: ["Q4 baseline metrics — need quarter-over-quarter comparison to validate the data flywheel. Ask author: what were Q4 FPR and TPR?", "Anomaly detection roadmap — Andrew flagged this as next priority. Ask author: what is the timeline and approach for unknown defect detection?", "Customer expansion pipeline — which other manufacturing customers are evaluating? Ask author: Q2 pilot commitments?"] },
        reliability: 97
      },
      "aud-eli-chen": {
        adaptedContent: "## Technical Due Diligence: Landing AI Visual Inspection Q1\n\n### Architecture Maturity Assessment\n\nThe two-stage pipeline (ResNet-50 primary + 3-model ensemble secondary) is production-grade for its scope. Key signals:\n\n**What's solid:**\n- Edge-first architecture on Jetson — right call for manufacturing latency requirements\n- Ensemble secondary stage with majority vote — reduces single-model failure modes\n- Active learning loop with quarterly retraining — the data flywheel is systematic, not ad-hoc\n- 67ms P99 is well within the line speed budget\n\n**What I'd probe:**\n- **No disclosed CI/CD for model updates.** How do new model versions get deployed to Jetson devices on the factory floor? Is there a staged rollout? Canary testing? Or is it manual firmware updates?\n- **Camera calibration drift.** No automated recalibration mentioned. Over months, lens degradation and environmental changes (lighting, dust) will shift the input distribution. Silent accuracy degradation.\n- **Monitoring gaps.** 99.7% TPR is measured how? On held-out test set or on production data? Is there real-time monitoring of prediction confidence distributions? A model can degrade silently if you're only measuring aggregate accuracy.\n\n### Build vs Buy Assessment\n\nThis is a strong internal capability. The data-centric approach (improving labels > improving models) is the right moat strategy — the models are commodity, the labeled defect data is the asset. A competitor can replicate the architecture in weeks. They cannot replicate 50K labeled defect images curated over years.\n\n### Risk Register\n\n1. **Single point of failure on Jetson.** What happens when the hardware fails mid-shift? Is there a fallback to human inspection?\n2. **Labeling quality.** Active learning assumes human labels are ground truth. If labelers disagree on edge cases, the training signal is noisy.\n3. **Regulatory.** If this is used in medical device or automotive manufacturing, the inspection system itself may need FDA/ISO certification.\n\n### Verdict\n\nProduction-mature for known defect categories. Missing: model deployment pipeline, drift detection, and anomaly detection for novel defects. These are the next three engineering investments.",
        rationale: { kept: ["Two-stage pipeline architecture — the core technical approach", "Key metrics with specific values", "Active learning loop — the data flywheel"], simplified: ["Marketing claims → verified architectural assessment"], expanded: ["Deployment pipeline gap (CI/CD for model updates)", "Drift detection concern", "Build vs buy analysis — the moat is data, not models", "Risk register with 3 specific risks"], cut: ["Business ROI", "Customer success narratives", "Market positioning"], terminologyChanges: [{ original: "AI-powered inspection", adapted: "two-stage pipeline (ResNet-50 + ensemble)", reason: "Architectural specificity" }, { original: "industry-leading", adapted: "production-grade for its scope", reason: "Honest assessment, not marketing" }, { original: "real-time", adapted: "67ms P99 within line speed budget", reason: "Quantified and contextualized" }], gaps: [] },
        reliability: 96
      },
      "aud-mike-rubino": {
        adaptedContent: "## Landing AI Q1 Report: What It Tells Me About the Team\n\n### Builder Signal\n\nThis report was written by builders, not marketers. Three things tell me that:\n\n1. **They published the false positive rate (2.1%), not just the true positive rate.** Most teams only share the number that makes them look good. Sharing FPR shows intellectual honesty and engineering maturity.\n\n2. **They have an active learning loop.** This means they built the feedback infrastructure, not just the model. Building the unglamorous pipeline that makes the model better over time is a founder-quality engineering decision.\n\n3. **Edge deployment on Jetson.** They didn't just train a model in the cloud and call it done. They shipped it to the factory floor on constrained hardware. That's the hard part. That's where most teams quit.\n\n### What I'd Ask in an Interview\n\n- \"What was the hardest production bug you hit in Q1?\" — tells me how they handle real-world failure\n- \"How do you handle a novel defect type the model has never seen?\" — tells me if they've thought about failure modes\n- \"What would you build differently if you started over?\" — tells me self-awareness and learning velocity\n\n### Team Assessment\n\nThis is a team that ships to production, iterates on data quality, and deploys on constrained hardware. That's a rare combination. The missing piece: the report doesn't mention who built what. I want to see individual ownership signals — who designed the ensemble approach? Who built the active learning pipeline? Great teams have visible individual contributors, not anonymous reports.\n\n### Verdict\n\nStrong execution signal. Would interview the technical leads immediately.",
        rationale: { kept: ["The engineering decisions that signal builder quality", "Active learning loop — shows infrastructure thinking", "Edge deployment — shows willingness to do the hard thing"], simplified: ["Technical metrics → what they reveal about the team", "Architecture details → interview questions they'd generate"], expanded: ["Three specific builder signals extracted from the report", "Suggested interview questions", "Individual ownership observation"], cut: ["All technical architecture details — this persona evaluates people, not systems", "Statistical methodology", "Market analysis"], terminologyChanges: [{ original: "99.7% true positive rate", adapted: "they published the false positive rate too", reason: "The honesty signal matters more than the number" }, { original: "ensemble secondary stage", adapted: "built the unglamorous pipeline", reason: "Grit signal" }, { original: "Jetson edge inference", adapted: "shipped to the factory floor on constrained hardware", reason: "Execution signal" }], gaps: ["Individual contributors — who built what? Ask author: can you attribute key decisions to specific team members?", "Failure stories — the best builder signal is how they handle things going wrong. Ask author: what was the biggest production incident in Q1?", "Hiring plan — what roles are open? Ask author: what's the Q2 hiring roadmap?"] },
        reliability: 93
      }
    }
  },

  "doc-demo-gaia": {
    title: "Gaia Dynamics: US-China Tariff Impact Analysis — April 2026",
    documentType: "Compliance Brief",
    sectionCount: 4,
    conceptCount: 5,
    tag: "Trade Compliance",
    tagColor: "cyan",
    description: "AI-driven tariff compliance for US importers",
    organizations: [
      { id: "org-gaia-dynamics", name: "Gaia Dynamics", type: "company", description: "AI-powered trade compliance platform automating tariff analysis, HTS classification, and regulatory risk for US importers." },
      { id: "org-ai-fund", name: "AI Fund", type: "company", description: "Andrew Ng venture studio building AI-native companies." },
    ],
    adaptations: {
      "aud-steve-jony": {
        adaptedContent: "## Your Supply Chain Just Got More Expensive. Here's What To Do About It.\n\nNew US-China tariffs took effect March 2026. If your company imports electronics, semiconductors, or rare earth components, your costs just went up 15-25%.\n\nThis isn't a policy brief. It's a decision document.\n\n### Three Things You Need to Know\n\n**1. Which products are hit.** Consumer electronics components (HTS 8542): duty rate increased from 25% to 40%. Semiconductor manufacturing equipment (HTS 8486): new 15% duty where there was none. Rare earth magnets (HTS 8505): 30% duty, up from 10%.\n\n**2. The exemption window is closing.** There's a 90-day exclusion request window ending June 28, 2026. If your product qualifies (≤$5M annual import value, no domestic alternative), file NOW. After June 28, the full rate applies retroactively.\n\n**3. The real cost isn't the tariff.** It's the compliance overhead. Every shipment now requires country-of-origin verification, component-level tariff classification, and end-use documentation. Companies that automate this survive. Companies that do it manually drown in paperwork and penalties.\n\n### The Bottom Line\n\nFile your exclusion requests before June 28. Automate your classification pipeline. And start qualifying alternative suppliers in Vietnam and India — not because the tariffs will disappear, but because supply chain diversification is the only hedge that works regardless of policy.",
        rationale: { kept: ["Specific tariff rates and HTS codes — the actionable data", "Exemption deadline (June 28) — creates urgency", "Three-action framework — clear decision structure"], simplified: ["Full regulatory analysis → three things to know", "HTS classification methodology → specific product examples", "Compliance framework → 'automate or drown'"], expanded: ["Added the real cost insight (compliance overhead > tariff itself)", "Supply chain diversification recommendation", "Urgency framing around the June 28 deadline"], cut: ["Historical tariff rate tables", "Legislative process details", "WTO dispute analysis"], terminologyChanges: [{ original: "Harmonized Tariff Schedule classification", adapted: "which products are hit", reason: "Action-oriented, not procedural" }, { original: "de minimis exclusion threshold", adapted: "≤$5M annual import value", reason: "Concrete number vs legal term" }, { original: "rules of origin verification", adapted: "country-of-origin verification", reason: "Plain language" }], gaps: ["Company-specific exposure — this persona needs YOUR numbers. Ask author: what is your annual import value for affected HTS codes?", "Competitor response — what are peers doing? Ask author: have any competitors announced supply chain shifts?", "Board-ready financial impact — tariff cost increase as % of COGS. Ask author: what is your current landed cost breakdown?"] },
        reliability: 93
      },
      "aud-shreyas-linus": {
        adaptedContent: "## Tariff Classification Engine: Technical Review\n\n### The Data Problem\n\nUS-China tariff compliance requires classifying every imported component to a 10-digit HTS code. For a company importing 5,000 SKUs, that's 5,000 classification decisions, each with legal liability.\n\n**Current automated approaches:**\n- **Rule-based systems:** Map product descriptions to HTS codes via keyword matching. Fast, brittle. Fails on novel products or ambiguous descriptions. ~75% accuracy.\n- **ML classification:** Fine-tuned BERT on CBP ruling database (~50K labeled rulings). ~91% accuracy but confidence-calibration is poor — the model is confidently wrong on edge cases.\n- **Gaia's approach:** Hybrid — ML primary classifier + rule-based guardrails + mandatory human review for low-confidence classifications. Confidence threshold: if ML probability < 0.85, route to human. This catches the dangerous failure mode: high-confidence misclassification.\n\n### Architecture Trade-offs\n\n**Chose recall over precision for tariff classification.** A false positive (flagging a product that doesn't need review) costs time. A false negative (misclassifying a product) costs penalties — potentially 4x the duty owed plus criminal liability. The system is deliberately conservative.\n\n**No real-time classification.** Batch processing with 24-hour SLA. Trade-off: importers can't get instant classification, but the system has time for multi-model ensemble and human review. Right call for regulatory compliance.\n\n### What Could Break\n\n- **Regulatory drift** — tariff rates change faster than the training data updates\n- **Adversarial descriptions** — suppliers gaming product descriptions to avoid tariffs\n- **Cross-border complexity** — rules of origin for assembled goods with components from multiple countries\n\n### Verdict\n\nThe hybrid approach is the right architecture for a domain where false negatives have legal consequences. The 0.85 confidence threshold is reasonable. Missing: adversarial robustness testing and a regulatory change detection pipeline.",
        rationale: { kept: ["Classification accuracy comparison (75% vs 91% vs hybrid)", "Confidence threshold architecture (0.85)", "Recall-over-precision trade-off rationale"], simplified: ["Policy analysis → data problem framing", "Legal framework → technical architecture"], expanded: ["Failure mode analysis (regulatory drift, adversarial descriptions, cross-border)", "Explicit comparison of three classification approaches", "Verdict with architectural assessment"], cut: ["Tariff rate details — this audience cares about the classification engine, not the rates", "Legislative context", "Business impact analysis"], terminologyChanges: [{ original: "tariff compliance platform", adapted: "tariff classification engine", reason: "Names the core technical challenge" }, { original: "AI-powered compliance", adapted: "hybrid ML classifier + rule-based guardrails", reason: "Specific architecture" }, { original: "automated duty calculation", adapted: "batch processing with 24-hour SLA", reason: "Honest about latency" }], gaps: [] },
        reliability: 95
      },
      "aud-gary-seth": {
        adaptedContent: "## \"A Single Misclassified Shipment Cost Us $2.3 Million.\"\n\nThat's the hook. Every importer has this nightmare. Most just haven't had it yet.\n\n### Platform Playbook\n\n**LinkedIn (CFOs and supply chain leaders):**\n\"New US-China tariffs hit March 2026. Your electronics components just got 15-25% more expensive. But here's what nobody's talking about: the compliance overhead is costing more than the tariff itself. We automated our classification pipeline. Time per shipment: 45 minutes → 3 minutes. Penalty risk: eliminated.\"\n\n**Twitter/X (trade/policy audience):**\n\"Everyone's talking about the tariff rates. Nobody's talking about the June 28 exclusion deadline. If you import <$5M annually in affected categories, you can file for exemption. Clock is ticking. 🧵\"\n\n**Email campaign (importers):**\nSubject: \"Your June 28 deadline (US-China tariffs)\"\nBody: 3-step action plan. 1) Check if your HTS codes are affected. 2) File exclusion if eligible. 3) Automate classification before Q3 volume hits.\n\n### Campaign Arc\n\n**Day 1:** Horror story hook ($2.3M misclassification)\n**Day 2:** June 28 deadline urgency + action checklist\n**Day 3:** \"How we cut classification time from 45 min to 3 min\" case study\n\n### The Pitch\n\n\"Don't hire more compliance staff. Automate the 90% that's pattern-matching. Keep humans for the 10% that requires judgment.\"",
        rationale: { kept: ["The $2.3M penalty hook — fear drives action", "June 28 deadline — urgency creates conversion", "Time savings (45 min → 3 min) — tangible ROI"], simplified: ["Full tariff analysis → 3-step action plan", "HTS classification methodology → 'check if your codes are affected'", "Compliance framework → 'automate the 90%'"], expanded: ["Platform-specific angles (LinkedIn, Twitter, email)", "Campaign arc with horror story → urgency → solution", "Email subject line and body structure"], cut: ["ML model architecture", "Accuracy metrics and confidence thresholds", "Regulatory process details"], terminologyChanges: [{ original: "Harmonized Tariff Schedule", adapted: "your HTS codes", reason: "Possessive makes it personal" }, { original: "de minimis exclusion", adapted: "exemption for imports <$5M", reason: "Concrete threshold" }, { original: "automated classification pipeline", adapted: "cut classification time from 45 min to 3 min", reason: "Outcome metric > feature name" }], gaps: ["Real penalty amount — $2.3M is illustrative. Ask author: do we have a verified case study with actual penalty amounts?", "Named customer — 'we automated our pipeline' needs a real company. Ask author: which customer approved a case study?", "Competitive comparison — what do importers currently use? Ask author: top 3 tools/processes being replaced?"] },
        reliability: 90
      },
      "aud-trade-cfo": {
        adaptedContent: "## Financial Impact Summary: New US-China Tariffs\n\n### Bottom Line\n\n**Your import costs are going up 15-25% on affected categories, effective immediately.** Based on typical import volumes for electronics and semiconductor components, a mid-size importer is looking at $2-8M in additional annual duty costs.\n\n### Three Numbers You Need\n\n1. **$40 per unit increase** on consumer electronics components (HTS 8542) — duty rate jumped from 25% to 40%\n2. **June 28, 2026** — deadline to file exclusion requests. After this, full rates apply retroactively\n3. **90 days** — window to restructure sourcing before Q3 volume hits\n\n### What I Need From the Team\n\n- **Procurement:** Pull our top 20 SKUs by import value. Which HTS codes are affected?\n- **Legal:** File exclusion requests for anything under $5M annual import value by June 15 (2 weeks buffer)\n- **Finance:** Model the P&L impact at current volumes. What's our landed cost increase as % of COGS?\n\n### My Recommendation\n\nDon't absorb the cost. Don't pass it all to customers. Split: automate compliance classification to save $200-400K in operational overhead, file every eligible exclusion, and begin qualifying Vietnam/India alternatives for the top 5 affected SKUs.",
        rationale: { kept: ["Specific tariff rates and duty increases — the CFO needs exact numbers", "June 28 deadline — creates urgency for action", "Exclusion eligibility criteria — potential cost avoidance"], simplified: ["Full regulatory analysis → three numbers", "HTS classification → '$40 per unit increase'", "Compliance framework → team action items"], expanded: ["Estimated dollar impact ($2-8M annual)", "Three-way recommendation (automate + exclude + diversify)", "Department-specific action items"], cut: ["Regulatory process details", "Historical tariff tables", "WTO analysis"], terminologyChanges: [{ original: "Harmonized Tariff Schedule", adapted: "$40 per unit increase", reason: "CFO thinks in dollars, not codes" }, { original: "de minimis exclusion", adapted: "exclusion requests for under $5M", reason: "Dollar threshold > legal term" }, { original: "rules of origin verification", adapted: "restructure sourcing", reason: "Action, not process" }], gaps: ["Our specific exposure — what are OUR top affected SKUs and volumes? Ask procurement for data.", "Margin impact — what % of COGS does the tariff increase represent? Need finance to model this.", "Competitor response — are peers absorbing or passing through? Ask sales for market intel."] },
        reliability: 93
      },
      "aud-trade-counsel": {
        adaptedContent: "## Legal Analysis: March 2026 Tariff Actions — Compliance Requirements\n\n### Affected Classifications\n\n| HTS Code | Description | Prior Rate | New Rate | Effective |\n|---|---|---|---|---|\n| 8542 | Electronic integrated circuits | 25% | 40% | 2026-03-01 |\n| 8486 | Semiconductor manufacturing equipment | 0% | 15% | 2026-03-01 |\n| 8505 | Rare earth magnets | 10% | 30% | 2026-03-01 |\n\n### Exclusion Request Procedure\n\n**Eligibility:** Annual import value ≤$5M per HTS subheading AND no commercially available domestic alternative.\n\n**Filing window:** Opens 2026-04-01, closes 2026-06-28 (90 days). No extensions anticipated based on USTR guidance.\n\n**Required documentation:**\n1. Product description with HTS classification rationale\n2. Import volume data (prior 3 years)\n3. Domestic sourcing analysis (evidence of no viable alternative)\n4. Economic impact statement\n\n**Penalty exposure for misclassification:** Section 592 penalties — 4x duty owed (negligence) to 8x (gross negligence) plus potential criminal referral for fraud. The new tariff rates amplify penalty exposure proportionally.\n\n### Recommended Actions\n\n1. Audit current classifications for ALL China-origin imports by June 1\n2. File exclusion requests for eligible subheadings by June 15 (buffer before deadline)\n3. Implement automated classification verification to reduce misclassification penalty risk\n4. Document country-of-origin analysis for all components in assembled products (anti-circumvention)",
        rationale: { kept: ["Specific HTS codes and rates — must be exact for filings", "Penalty exposure calculations — quantified legal risk", "Filing deadlines with exact dates"], simplified: ["Nothing simplified — legal counsel needs full regulatory precision"], expanded: ["Added penalty calculation (4x to 8x duty owed)", "Added anti-circumvention requirement for assembled products", "Added classification audit recommendation"], cut: ["Market commentary", "Strategic sourcing recommendations — that's ops, not legal", "Cost impact estimates — that's finance"], terminologyChanges: [], gaps: [] },
        reliability: 97
      },
      "aud-trade-ops": {
        adaptedContent: "## Supply Chain Impact Assessment: US-China Tariff Changes\n\n### Which Suppliers Are Hit\n\nAny supplier with China-origin components in these categories:\n- **PCB components and ICs** — 25% → 40% duty. This hits our Shenzhen suppliers directly.\n- **Semiconductor equipment** — new 15% duty. Affects capital equipment purchases from Chinese OEMs.\n- **Rare earth magnets** — 10% → 30%. Motor and sensor components.\n\n### Lead Time Impact\n\nIf we shift sourcing to Vietnam/India alternatives:\n- **Vietnam:** 6-8 week qualification cycle for existing component specs. Lead times 2-3 weeks longer than Shenzhen. Quality comparable for PCB assembly.\n- **India:** 8-12 week qualification. Lead times 3-4 weeks longer. Strong on passive components, weaker on ICs.\n- **Mexico (nearshoring):** 4-6 week qualification. Lead times cut by 50% vs Asia. Limited IC capability but strong for assembly.\n\n### Inventory Strategy\n\n**Immediate (next 30 days):** Build 90-day safety stock on affected components at current rates before suppliers adjust pricing.\n\n**Medium-term (60-90 days):** Qualify top 5 alternative suppliers. Dual-source critical components.\n\n**Long-term:** Shift 40-60% of affected volume to non-China sources by Q4. Don't go 100% — maintain China as backup for surge capacity.\n\n### The Real Risk\n\nIt's not the tariff cost — it's supply chain fragility. Single-source from China + tariff volatility = one policy change away from margin collapse. Diversification isn't optional anymore.",
        rationale: { kept: ["Specific affected component categories", "Alternative supplier qualification timelines", "Safety stock recommendation"], simplified: ["Tariff rate tables → 'which suppliers are hit'", "HTS codes → component categories ops teams recognize", "Regulatory language → logistics language"], expanded: ["Vietnam/India/Mexico sourcing comparison with qualification timelines", "Three-phase inventory strategy (immediate/medium/long)", "Real risk framing — fragility, not just cost"], cut: ["Legal filing procedures — that's counsel's job", "Financial modeling — that's finance's job", "Regulatory process details"], terminologyChanges: [{ original: "HTS 8542", adapted: "PCB components and ICs", reason: "Ops thinks in parts, not codes" }, { original: "exclusion request window", adapted: "before suppliers adjust pricing", reason: "Market timing > regulatory timing" }, { original: "tariff rate increase", adapted: "supply chain fragility", reason: "The systemic risk matters more than the number" }], gaps: ["Current supplier list — which specific suppliers are affected? Need procurement data.", "Qualification costs — what does it cost to qualify a new Vietnam supplier? Ask engineering.", "Demand forecast — what's Q3-Q4 volume? Need this to size the safety stock build."] },
        reliability: 91
      }
    }
  },

  "doc-demo-health": {
    title: "Phase II Clinical Trial Protocol: AI-Identified Compound AX-7 for Treatment-Resistant Depression",
    documentType: "Clinical Protocol",
    sectionCount: 6,
    conceptCount: 5,
    tag: "Healthcare AI",
    tagColor: "emerald",
    description: "AI-accelerated drug discovery for mental health",
    organizations: [
      { id: "org-ai-fund", name: "AI Fund", type: "company", description: "Andrew Ng venture studio building AI-native companies across healthcare, manufacturing, and enterprise verticals." },
    ],
    adaptations: {
      "aud-steve-jony": {
        adaptedContent: "## 47 Million Americans Tried Every Antidepressant. Nothing Worked. Until Now.\n\nTreatment-resistant depression affects 30% of people with major depression. That's 47 million Americans who tried medication after medication — SSRIs, SNRIs, tricyclics, MAOIs — and none of them worked. They didn't fail to take their medicine. The medicine failed them.\n\n### What Changed\n\nAI analyzed 2.3 million molecular structures and identified a compound — AX-7 — that works through a mechanism no human researcher had considered. It targets the glutamate system instead of serotonin, which is what every antidepressant since Prozac has targeted.\n\nThe Phase I trial showed something remarkable: **68% of patients who had failed 3+ prior medications responded to AX-7 within 6 weeks.** Not a modest improvement. A transformation.\n\n### What Happens Next\n\nPhase II starts Q3 2026 with 340 patients across 12 sites. The primary question: does the Phase I signal hold at scale? Secondary questions: optimal dosing, duration of effect, safety in older adults.\n\n### Why This Matters Beyond Depression\n\nIf AI can find what human researchers missed in the most-studied therapeutic area in psychiatry, it can find treatments for diseases where we're not even looking in the right direction. AX-7 isn't just a drug. It's proof that AI-driven drug discovery finds what humans can't — because it has no assumptions about where to look.",
        rationale: { kept: ["68% response rate in treatment-resistant patients — the breakthrough number", "Novel mechanism (glutamate vs serotonin) — what makes it different", "47M affected Americans — the human scale"], simplified: ["Molecular screening methodology → 'analyzed 2.3M structures'", "Glutamatergic NMDA receptor modulation → 'targets the glutamate system'", "Pharmacokinetic profile → 'responded within 6 weeks'"], expanded: ["Human impact framing (47M Americans, medicine failed them)", "Broader implications for AI-driven drug discovery", "Emotional narrative arc"], cut: ["Inclusion/exclusion criteria", "Statistical analysis methodology", "Adverse event categorization tables"], terminologyChanges: [{ original: "treatment-resistant major depressive disorder", adapted: "tried every antidepressant and nothing worked", reason: "Patient experience, not clinical label" }, { original: "glutamatergic NMDA receptor modulator", adapted: "works through a mechanism no one had considered", reason: "The surprise is the story" }, { original: "Phase II randomized controlled trial", adapted: "testing in 340 patients across 12 sites", reason: "Scale and scope, not study design jargon" }], gaps: ["Patient story — this persona needs a human face. Ask author: can we profile one patient from Phase I (with consent)?", "Cost of treatment-resistant depression — what does society spend on patients who don't respond? Ask author: annual healthcare cost per TRD patient?", "Timeline to market — when could this reach patients? Ask author: projected FDA approval timeline?"] },
        reliability: 92
      },
      "aud-shreyas-linus": {
        adaptedContent: "## Phase II Protocol Review: AX-7 (Glutamatergic Modulator)\n\n### Compound Discovery Pipeline\n\nAX-7 was identified through a graph neural network (GNN) screening 2.3M molecular structures against a knowledge graph of known drug-target interactions. The GNN predicted binding affinity to NMDA receptor subtypes (NR2B-selective) with a novel allosteric mechanism.\n\n**Key technical differentiator:** Traditional virtual screening uses molecular docking (physics-based). The GNN approach captures learned representations of molecular interaction patterns from historical data. Trade-off: faster screening (2.3M compounds in 72 hours vs. months) but less interpretable binding predictions.\n\n### Phase I Results\n\n| Metric | Value |\n|---|---|\n| N | 48 (4 dose cohorts) |\n| Response rate (≥50% MADRS reduction) | 68% at optimal dose |\n| Remission rate | 41% |\n| Time to response | Median 4.2 weeks |\n| Serious adverse events | 2 (hepatic enzyme elevation, resolved) |\n| Dropout rate | 12% |\n\n### Phase II Design\n\n- **Design:** Randomized, double-blind, placebo-controlled, 3-arm (low dose, high dose, placebo)\n- **N:** 340 (powered for 0.35 effect size, α=0.05, β=0.80)\n- **Primary endpoint:** MADRS score change at Week 8\n- **Key secondary:** Sustained response at Week 24\n- **Sites:** 12 academic medical centers\n\n### What Could Break\n\n- **Hepatic signal** — 2/48 in Phase I is a 4.2% rate. If this holds or worsens in Phase II, it's a safety concern that could require dose modification or monitoring protocols\n- **Placebo response** — TRD trials have notoriously high placebo response rates (30-40%). The 68% response must hold a significant delta over placebo\n- **NR2B selectivity** — if the compound has off-target NMDA activity, cognitive side effects (dissociation, memory) could emerge at scale\n\n### Verdict\n\nWell-designed Phase II with appropriate powering. The GNN discovery pipeline is a genuine advance over traditional screening. The hepatic signal is the key risk to monitor. If the placebo-controlled delta holds at ≥25 percentage points, this is a significant therapeutic advance.",
        rationale: { kept: ["Phase I metrics table — the data that matters", "GNN discovery pipeline architecture", "Phase II design parameters"], simplified: ["Regulatory background → study design specifics", "Mechanism of action prose → NR2B-selective allosteric mechanism"], expanded: ["Failure mode analysis (hepatic signal, placebo response, off-target effects)", "Technical comparison: GNN vs traditional docking", "Verdict with specific threshold (25pp delta)"], cut: ["Patient population demographics", "Ethical approval details", "Comparator drug history"], terminologyChanges: [{ original: "AI-identified compound", adapted: "GNN-screened from 2.3M structures", reason: "Name the actual method" }, { original: "novel mechanism of action", adapted: "NR2B-selective allosteric modulator", reason: "Specific target" }, { original: "promising Phase I results", adapted: "68% response, 41% remission, 4.2% hepatic SAE rate", reason: "Numbers, not adjectives" }], gaps: [] },
        reliability: 97
      },
      "aud-gary-seth": {
        adaptedContent: "## \"I Tried 7 Antidepressants in 4 Years. Number 8 Was Found by AI.\"\n\nThat's the patient story that launches the campaign. 47 million Americans with treatment-resistant depression. Every single one has a version of this story.\n\n### Platform Playbook\n\n**LinkedIn (healthcare executives + investors):**\n\"30% of depression patients don't respond to ANY available medication. That's a $47B unmet market. Our AI screened 2.3M molecular structures and found a compound that works through a mechanism human researchers never considered. Phase I: 68% response rate in patients who failed 3+ prior drugs. Phase II starts Q3.\"\n\n**Twitter/X (AI + biotech audience):**\n\"A graph neural network screened 2.3M compounds in 72 hours. Found a glutamate-targeting antidepressant that works where serotonin-based drugs fail. 68% response rate in treatment-resistant patients. The AI didn't have preconceptions about where to look. That's the point. 🧵\"\n\n**Patient advocacy + media:**\nDon't lead with the science. Lead with Sarah (composite patient). 4 years, 7 medications, none worked. Enrolled in the trial expecting nothing. Week 4, she noticed she could laugh at her daughter's jokes again. THAT is the story that 60 Minutes runs.\n\n### Campaign Arc\n\n**Day 1:** Patient story (Sarah) + \"AI found what doctors couldn't\"\n**Day 2:** The science — 2.3M compounds, 72 hours, glutamate mechanism\n**Day 3:** The market — $47B unmet need, Phase II recruiting\n\n### The Pitch\n\n\"AI doesn't cure depression. It finds the molecule that does — by looking where no human thought to look.\"",
        rationale: { kept: ["68% response rate — the proof point", "47M affected patients — the market/human scale", "Novel mechanism angle — AI found what humans missed"], simplified: ["GNN architecture → 'screened 2.3M compounds in 72 hours'", "NMDA receptor pharmacology → 'works through a mechanism nobody considered'", "Clinical protocol → 'Phase II starts Q3'"], expanded: ["Patient narrative (Sarah composite) for media/advocacy", "Platform-specific angles (LinkedIn, Twitter, media)", "Campaign arc: story → science → market"], cut: ["Phase II statistical design", "Adverse event profiles", "Regulatory pathway details"], terminologyChanges: [{ original: "treatment-resistant major depressive disorder", adapted: "tried 7 antidepressants and none worked", reason: "Patient voice" }, { original: "glutamatergic NMDA receptor modulator", adapted: "works where serotonin-based drugs fail", reason: "Contrast frame" }, { original: "graph neural network virtual screening", adapted: "AI screened 2.3M compounds in 72 hours", reason: "Speed and scale are the hook" }], gaps: ["Real patient story — Sarah is a composite. Ask author: do we have a consented patient willing to share their experience?", "Investor deck — the $47B market claim needs a cited source. Ask author: which market research report?", "Phase II recruitment — if we're driving awareness, include the enrollment link. Ask author: is the trial registered on ClinicalTrials.gov?"] },
        reliability: 91
      },
      "aud-health-cmo": {
        adaptedContent: "## Clinical Assessment: AX-7 for Treatment-Resistant Depression\n\n### Should This Enter Our Formulary Discussion?\n\n**Yes, with caveats.** The Phase I data warrants attention but not action yet.\n\n### The Efficacy Signal\n\n68% response rate (≥50% MADRS reduction) in patients who failed 3+ prior medications. For context, our current best option for TRD patients — esketamine nasal spray — shows ~50-55% response in similar populations. If AX-7's signal holds in Phase II, this is a meaningful advance.\n\nRemission rate: 41%. Time to response: median 4.2 weeks. Both clinically relevant — our TRD patients currently wait 8-12 weeks for augmentation strategies to show effect.\n\n### Safety Considerations\n\n**Hepatic signal: 2 out of 48 patients (4.2%) had transaminase elevations.** Both resolved without intervention, but this needs close monitoring in Phase II. If the rate holds or worsens, we'd need a hepatic monitoring protocol — baseline and monthly LFTs, which adds cost and patient burden.\n\nNo cognitive side effects reported, which distinguishes AX-7 from ketamine-derived treatments.\n\n### My Recommendation\n\nMonitor Phase II results (expected Q2 2027). If the placebo-controlled delta is ≥20 percentage points AND the hepatic signal doesn't worsen, bring to P&T committee for formulary consideration. Don't commit resources until we have controlled data.",
        rationale: { kept: ["Response and remission rates — the efficacy proof", "Hepatic safety signal — the key risk", "Comparison to esketamine — the clinical benchmark"], simplified: ["Molecular mechanism → focused on clinical outcome", "GNN discovery → irrelevant to formulary decision"], expanded: ["Compared to current TRD standard of care", "Added monitoring protocol recommendation", "P&T committee timeline"], cut: ["Drug discovery methodology — irrelevant to clinical use", "Market sizing — CMO doesn't think in TAM", "AI angle — the molecule matters, not how it was found"], terminologyChanges: [{ original: "glutamatergic NMDA receptor modulator", adapted: "novel mechanism distinct from serotonergic agents", reason: "Clinical framing" }, { original: "graph neural network screening", adapted: "the molecule", reason: "The CMO prescribes molecules, not algorithms" }, { original: "Phase II randomized controlled trial", adapted: "controlled data", reason: "Concise clinical language" }], gaps: ["Head-to-head comparison — how does AX-7 compare to esketamine in the same population? Ask author: are there plans for a comparator arm?", "Cost projection — what will AX-7 cost per patient per month? Ask author: anticipated pricing strategy?", "Formulary pathway — does this require REMS? Ask author: any FDA signals on distribution restrictions?"] },
        reliability: 95
      },
      "aud-health-researcher": {
        adaptedContent: "## Protocol Review: AX-7 Phase II — Methodological Assessment\n\n### Study Design\n\nRandomized, double-blind, placebo-controlled, 3-arm (low dose, high dose, placebo). N=340, powered for effect size 0.35 (α=0.05, β=0.80). Primary endpoint: MADRS change at Week 8. Key secondary: sustained response at Week 24. 12 academic medical centers.\n\n**Design is appropriate.** Three-arm captures dose-response. MADRS is the standard instrument for TRD. Week 8 primary is reasonable for a glutamatergic mechanism — faster than SSRIs, slower than ketamine.\n\n### Methodological Concerns\n\n1. **Placebo response in TRD trials.** Meta-analyses show 30-40% placebo response rates in TRD populations. The 68% Phase I response (uncontrolled) could shrink to 25-30% delta in controlled conditions. Power calculation assumes 0.35 effect size — tight but achievable if the mechanism is genuine.\n\n2. **Confounder: concurrent medications.** Protocol allows stable-dose concurrent antidepressants. This is pragmatic but introduces a confound — is AX-7 effective as monotherapy or only as augmentation? Without a monotherapy arm, we can't answer this.\n\n3. **Hepatic monitoring.** 4.2% transaminase elevation in Phase I (N=48) is a wide confidence interval. Phase II will narrow this — if the rate is <2% at N=340, it's likely clinically manageable. If it's >5%, it's a development risk.\n\n4. **Dropout rate.** 12% in Phase I. Acceptable, but Phase II over 24 weeks will be higher. LOCF vs MMRM analysis choice matters here — protocol should specify MMRM as primary.\n\n### What I'd Want to See\n\n- Pre-registered statistical analysis plan (SAP)\n- Independent Data Safety Monitoring Board (DSMB) charter\n- Centralized MADRS rater training to reduce inter-site variability\n\n### Verdict\n\nWell-powered, appropriately designed for its phase. The uncontrolled Phase I signal is promising but the real test is the placebo-controlled delta. Key methodological risk: high placebo response rate eroding the effect size.",
        rationale: { kept: ["Full study design parameters", "Power calculation and effect size", "Phase I efficacy data"], simplified: ["Nothing — this audience wants full methodological detail"], expanded: ["Placebo response rate concern with meta-analytic context", "Concurrent medication confounder analysis", "Statistical methodology recommendations (MMRM vs LOCF)", "Three specific requests (SAP, DSMB, rater training)"], cut: ["Patient narratives — this is a science review", "Market sizing", "AI discovery methodology — irrelevant to protocol quality"], terminologyChanges: [], gaps: [] },
        reliability: 98
      },
      "aud-health-advocate": {
        adaptedContent: "## A New Treatment for Depression That Didn't Respond to Anything Else\n\n### What Is This?\n\nResearchers found a new medicine — called AX-7 — that may help people whose depression didn't get better with other medications. About 1 in 3 people with depression fall into this category. That's 47 million Americans.\n\n### Does It Work?\n\nIn the first small study (48 people), **68% of patients felt significantly better within 6 weeks.** These were people who had already tried 3 or more other antidepressants without success. That's a hopeful number — but it's early.\n\n### Is It Safe?\n\nSo far, the side effects have been manageable. A small number of patients showed changes in liver function tests, but these went back to normal. The larger study (340 patients) will give us a much clearer picture of safety.\n\n### What's Different About This Medicine?\n\nMost antidepressants target serotonin — the same system Prozac targets, which was discovered in the 1980s. AX-7 works on a completely different system in the brain. That's why it might help people who didn't respond to the usual medications.\n\n### When Can Patients Access It?\n\nThe next study starts in Q3 2026. If it goes well, the medicine could be available in 3-5 years after FDA review. We know that feels like a long time when you're suffering. But this is moving faster than most drug development.\n\n### How Can Patients Participate?\n\nThe Phase II trial is enrolling 340 patients across 12 hospitals. If you or someone you know has tried 3+ antidepressants without adequate response, you may be eligible.\n\n**The most important thing:** There is hope. Research hasn't given up on the people the current medications can't help.",
        rationale: { kept: ["68% response rate — hope, backed by data", "47 million affected — you are not alone", "The mechanism difference — why this might work when others didn't"], simplified: ["'MADRS score reduction' → 'felt significantly better'", "'glutamatergic NMDA modulation' → 'works on a completely different system'", "'Phase II RCT' → 'next study with 340 patients'"], expanded: ["Enrollment information — how to participate", "Timeline expectations — honest about 3-5 years", "Emotional framing — hope without hype"], cut: ["ALL statistical methodology — patients don't need p-values", "Study design parameters — they need to know it's rigorous, not how", "Molecular biology — 'different system in the brain' is enough"], terminologyChanges: [{ original: "treatment-resistant major depressive disorder", adapted: "depression that didn't respond to anything else", reason: "Their experience, not a diagnosis code" }, { original: "MADRS score reduction ≥50%", adapted: "felt significantly better", reason: "Outcome they can feel" }, { original: "glutamatergic mechanism", adapted: "completely different system in the brain", reason: "Honest simplification without condescension" }], gaps: ["Enrollment link — where do patients sign up? Ask author: ClinicalTrials.gov ID and enrollment contact?", "Patient support resources — what support exists during the trial? Ask author: is there a patient navigator or support line?", "Cost to patients — will the trial medication be free? Ask author: what are the financial terms for participants?"] },
        reliability: 94
      }
    }
  }
};

export function getDemoDoc(documentId: string): DemoDoc | undefined {
  return DEMO_DOCS[documentId];
}

export function getCachedAdaptation(documentId: string, audienceId: string): (CachedAdaptation & { audienceName: string; formatName: string }) | undefined {
  const doc = DEMO_DOCS[documentId];
  if (!doc) return undefined;
  const adaptation = doc.adaptations[audienceId];
  if (!adaptation) return undefined;
  return {
    ...adaptation,
    audienceName: AUDIENCE_NAMES[audienceId] || audienceId,
    formatName: "Executive Summary"
  };
}

export function getAllDemoDocs(): { id: string; doc: DemoDoc }[] {
  return Object.entries(DEMO_DOCS).map(([id, doc]) => ({ id, doc }));
}

export function isDemoDoc(documentId: string): boolean {
  return documentId in DEMO_DOCS;
}

export function getDemoOrganizations(documentId: string): DemoOrg[] {
  return DEMO_DOCS[documentId]?.organizations ?? [];
}
